// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCihfuMVuK0syoGyWc6azT9-59rM2EVcAU',
    appId: '1:339576007174:web:54b61666778ecadb013187',
    messagingSenderId: '339576007174',
    projectId: 'phygen-ai',
    authDomain: 'phygen-ai.firebaseapp.com',
    storageBucket: 'phygen-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnye-8lopYxG-u5q0RQ3y2xTM4IkUN3mo',
    appId: '1:339576007174:android:93ee14c5fe90bc47013187',
    messagingSenderId: '339576007174',
    projectId: 'phygen-ai',
    storageBucket: 'phygen-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV_MYRpqtMoTaGUEOTp07bmLAprYrBF4c',
    appId: '1:339576007174:ios:8ebfd6388ed2543f013187',
    messagingSenderId: '339576007174',
    projectId: 'phygen-ai',
    storageBucket: 'phygen-ai.firebasestorage.app',
    androidClientId: '339576007174-iqec6c4mjob2f849cr81aqta16klscu7.apps.googleusercontent.com',
    iosClientId: '339576007174-i789u23a0att9h2cvovnelkmmrsco2j4.apps.googleusercontent.com',
    iosBundleId: 'com.example.phygen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV_MYRpqtMoTaGUEOTp07bmLAprYrBF4c',
    appId: '1:339576007174:ios:8ebfd6388ed2543f013187',
    messagingSenderId: '339576007174',
    projectId: 'phygen-ai',
    storageBucket: 'phygen-ai.firebasestorage.app',
    androidClientId: '339576007174-iqec6c4mjob2f849cr81aqta16klscu7.apps.googleusercontent.com',
    iosClientId: '339576007174-i789u23a0att9h2cvovnelkmmrsco2j4.apps.googleusercontent.com',
    iosBundleId: 'com.example.phygen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCihfuMVuK0syoGyWc6azT9-59rM2EVcAU',
    appId: '1:339576007174:web:9c999b24a687f7a3013187',
    messagingSenderId: '339576007174',
    projectId: 'phygen-ai',
    authDomain: 'phygen-ai.firebaseapp.com',
    storageBucket: 'phygen-ai.firebasestorage.app',
  );

}